### ISSUE TITLE
nopCommerceMobile Web API

### ISSUE THREAD

**Issue by hathanhhung** [GomeniucIvan/nopCommerceMobile#1]
Dear Bro,
Why I don't see any Web API Which make a connector between nopCommerceMobile and nopCommerce. 
Currently, Has this version just make offline data with nopCommerce ? 
Could you please give me some advice !?

**Comment by GomeniucIvan** [comment]
Hi, 
copy the api folder from _src/Presentation/Nop.Web/Controllers/_ to your nopcommerce project or download current project [nopcommerceMobileApi](https://github.com/GomeniucIvan/nopCommerceWebApi)

**Comment by hathanhhung** [comment]
> Hi,
> copy the api folder from _src/Presentation/Nop.Web/Controllers/_ to your nopcommerce project or download current project [nopcommerceMobileApi](https://github.com/GomeniucIvan/nopCommerceMobileApi)

Many thanks !
